### ISSUE TITLE
node is too long and inconvenient to use.

### ISSUE THREAD

**Issue by hahajaja** [tritant/ComfyUI_CreaPrompt#3]
Can the node be divided into multiple nodes? A single node is too long and inconvenient to use.

**Comment by tritant** [comment]
In this case, additional nodes would have to be used to concatenate the result of the different nodes. It's possible, but I don't have time to make improvements.
But what you can do is remove the categories (.csv file) that you are not using from the csv folder, they will automatically be removed from the node, which will shorten it.

**Comment by tritant** [comment]
Hi, look the update, now you can configure Multiple nodes(four)

**Comment by hahajaja** [comment]
@tritant  Your hard work has been very helpful. Thanks for always doing more than what's expected.
