### ISSUE TITLE
Weighting the prompt

### ISSUE THREAD

**Issue by Latentnaut** [tritant/ComfyUI_CreaPrompt#4]
I love this node, excellent idea!!

Is there a chance to weight each part of the prompt?

(strong lighting:1.5)

**Comment by tritant** [comment]
Hi, thanks for your feedback. This would mean adding a field under each category to be able to choose the weight. I'm not sure this is a good idea, it would make the node twice as big, it's already too big.

**Comment by tritant** [comment]
Look the update, i have added a node with weight, configure it in csv+weight folder

![Capture d'écran 2024-07-17 083300](https://github.com/user-attachments/assets/5e4d748b-4078-4a6b-a836-2e724ab682cc)

**Comment by Latentnaut** [comment]
Awesome!!
