### ISSUE TITLE
Even with a fixed seed, new prompts are generated.

### ISSUE THREAD

**Issue by n0855188** [tritant/ComfyUI_CreaPrompt#8]
In `CreaPrompt complete node` nodes, new prompts are generated even when the seed is fixed.

**Comment by tritant** [comment]
Hello, what is the point of keeping the same prompt and the same seed, the image will be exactly the same

**Comment by n0855188** [comment]
Hi, once I find a good prompt,  I'd like to keeping the same prompt while making minor adjustments, such as changing parameters or upscaling, to refine the output.

**Comment by tritant** [comment]
In this case, you must copy the prompt and the seed and use them in a manual WF

**Comment by n0855188** [comment]
Got it.
