### ISSUE TITLE
CreaPrompt.IS_CHANGED() got an unexpected keyword argument 'Man'

### ISSUE THREAD

**Issue by tampadesignr** [tritant/ComfyUI_CreaPrompt#9]
CreaPrompt.IS_CHANGED() got an unexpected keyword argument 'Man'

no man is chosen yet that happens

update..
tested other nodes and all have some kind of 
CreaPrompt.IS_CHANGED() got an unexpected keyword argument

think comfyui update broke something

**Comment by tritant** [comment]
I'll try to reproduce this error when I have some time.

**Comment by tritant** [comment]
Fixed in all nodes

**Comment by tampadesignr** [comment]
woot woot... awesome thank you
and thank you for your node and work
